[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         tail
    Path         /var/log/app/auth.log
    Tag          auth.events
    Refresh_Interval 1

[FILTER]
    Name         parser
    Match        auth.events
    Key_Name     log
    Parser       regex_auth

[OUTPUT]
    Name         opensearch
    Match        auth.events
    Host         opensearch
    Port         9200
    Index        security_events
    Type         _doc
